---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-training-config
data:
  script.js: |
    import http from 'k6/http';
    import { sleep } from 'k6';

    let test_duration = "1m";

    export const options = {
        vus: 1,
        duration: test_duration,
      };

    let get_params = {
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
        },
    };

    let post_params = {
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Api-Token ${__ENV.K6_DYNATRACE_APITOKEN}`
      },
    };

    export default function main_load_test() {
      // Your main test here
      // For example, a simple GET request
      http.get('https://CODESPACE_NAME_PLACEHOLDER-8080.GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN_PLACEHOLDER', get_params);
      sleep(1);
    }

    export function teardown() {
      // Send SDLC event at the end of the test
      let payload = {
        "event.provider": "k6",
        "event.type": "test",
        "event.category": "finished",
        "training": `${__ENV.TRAINING_MODE}`,
        "duration": test_duration
      }
      let res = http.post(`${__ENV.K6_DYNATRACE_URL}/platform/ingest/v1/events.sdlc`, JSON.stringify(payload), post_params);
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-training-run1
spec:
  template:
    spec:
      containers:
      - name: k6
        image: hrexed/xk6-dynatrace-output:0.11
        args: ["run", "/script.js", "-o", "output-dynatrace"]
        volumeMounts:
        - name: config-volume
          mountPath: /script.js
          subPath: script.js
        env:
          - name: K6_DYNATRACE_URL
            valueFrom:
              secretKeyRef:
                name: dt-details
                key: DT_ENDPOINT_UC14
          - name: K6_DYNATRACE_APITOKEN
            valueFrom:
              secretKeyRef:
                name: dt-details
                key: DT_API_TOKEN_UC14
          - name: TRAINING_MODE
            value: "true"
      volumes:
        - name: config-volume
          configMap:
            name: k6-training-config
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-training-run2
spec:
  template:
    spec:
      containers:
      - name: k6
        image: hrexed/xk6-dynatrace-output:0.11
        args: ["run", "/script.js", "-o", "output-dynatrace"]
        volumeMounts:
        - name: config-volume
          mountPath: /script.js
          subPath: script.js
        env:
          - name: K6_DYNATRACE_URL
            valueFrom:
              secretKeyRef:
                name: dt-details
                key: DT_ENDPOINT_UC14
          - name: K6_DYNATRACE_APITOKEN
            valueFrom:
              secretKeyRef:
                name: dt-details
                key: DT_API_TOKEN_UC14
      volumes:
        - name: config-volume
          configMap:
            name: k6-training-config
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-training-run3
spec:
  template:
    spec:
      containers:
      - name: k6
        image: hrexed/xk6-dynatrace-output:0.11
        args: ["run", "/script.js", "-o", "output-dynatrace"]
        volumeMounts:
        - name: config-volume
          mountPath: /script.js
          subPath: script.js
        env:
          - name: K6_DYNATRACE_URL
            valueFrom:
              secretKeyRef:
                name: dt-details
                key: DT_ENDPOINT_UC14
          - name: K6_DYNATRACE_APITOKEN
            valueFrom:
              secretKeyRef:
                name: dt-details
                key: DT_API_TOKEN_UC14
          - name: TRAINING_MODE
            value: "true"
      volumes:
        - name: config-volume
          configMap:
            name: k6-training-config
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-training-run4
spec:
  template:
    spec:
      containers:
      - name: k6
        image: hrexed/xk6-dynatrace-output:0.11
        args: ["run", "/script.js", "-o", "output-dynatrace"]
        volumeMounts:
        - name: config-volume
          mountPath: /script.js
          subPath: script.js
        env:
          - name: K6_DYNATRACE_URL
            valueFrom:
              secretKeyRef:
                name: dt-details
                key: DT_ENDPOINT_UC14
          - name: K6_DYNATRACE_APITOKEN
            valueFrom:
              secretKeyRef:
                name: dt-details
                key: DT_API_TOKEN_UC14
          - name: TRAINING_MODE
            value: "true"
      volumes:
        - name: config-volume
          configMap:
            name: k6-training-config
      restartPolicy: Never
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-training-run5
spec:
  template:
    spec:
      containers:
      - name: k6
        image: hrexed/xk6-dynatrace-output:0.11
        args: ["run", "/script.js", "-o", "output-dynatrace"]
        volumeMounts:
        - name: config-volume
          mountPath: /script.js
          subPath: script.js
        env:
          - name: K6_DYNATRACE_URL
            valueFrom:
              secretKeyRef:
                name: dt-details
                key: DT_ENDPOINT_UC14
          - name: K6_DYNATRACE_APITOKEN
            valueFrom:
              secretKeyRef:
                name: dt-details
                key: DT_API_TOKEN_UC14
          - name: TRAINING_MODE
            value: "true"
      volumes:
        - name: config-volume
          configMap:
            name: k6-training-config
      restartPolicy: Never
